# Dependabot configuration for automated dependency updates
# Documentation: https://docs.github.com/en/code-security/dependabot

version: 2
updates:
  # Enable version updates for npm packages in root
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "olane-labs/core-team"
    assignees:
      - "olane-labs/core-team"
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group updates for better management
    groups:
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "ts-*"
      eslint:
        patterns:
          - "eslint*"
          - "@typescript-eslint/*"
      jest:
        patterns:
          - "jest*"
          - "@types/jest"
          - "ts-jest"
      build-tools:
        patterns:
          - "webpack*"
          - "babel*"
          - "aegir"

  # Enable version updates for npm packages in workspace packages
  - package-ecosystem: "npm"
    directory: "/packages/o-core"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "o-core"

  - package-ecosystem: "npm"
    directory: "/packages/o-node"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "o-node"

  # Add more workspace packages as needed

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    reviewers:
      - "olane-labs/core-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"

