/**
 * Bidirectional message envelope flowing through `AgentNode` inboxes.
 *
 * Shape is forward-compatible with A2A's `Message` + `Task` schemas:
 *  - `task` mirrors A2A `TaskState` so a future `o://a2a-bridge` can bridge
 *    task lifecycles without re-shaping.
 *  - `parts[]` mirrors A2A `Part` so multi-modal content (text, file refs,
 *    structured data) is supported from day 1.
 */
export interface InboxMessage {
  /** Stable message id — generated by the sender. */
  id: string;

  /** Olane address of the sender (e.g. `o://brendon/codex/abcd`). */
  from: string;

  /** Olane address of the receiver (e.g. `o://brendon/claude-code/1234`). */
  to: string;

  /** ISO 8601 timestamp the message entered the inbox. */
  sentAt: string;

  /** Message parts — text, file references, structured data. */
  parts: MessagePart[];

  /**
   * Optional task linkage so reply chains can be threaded together. A
   * sender that wants a reply correlated includes a `task.id` it owns;
   * the receiver echoes it on response.
   */
  task?: {
    id: string;
    state: TaskState;
  };

  /**
   * Optional caller-supplied correlation id distinct from the task id.
   * Useful when the sender wants a one-off ack without modeling the
   * exchange as a long-running task.
   */
  correlationId?: string;

  /** Free-form metadata (debugging, tracing, observability). */
  metadata?: Record<string, unknown>;
}

export interface MessagePart {
  /** Mirrors A2A `Part.kind`. */
  kind: 'text' | 'file' | 'data';
  /** Body for `kind: 'text'`. */
  text?: string;
  /** File reference for `kind: 'file'` — could be a path or a URI. */
  file?: {
    uri?: string;
    name?: string;
    mimeType?: string;
  };
  /** Structured payload for `kind: 'data'`. */
  data?: unknown;
}

/**
 * A2A-shaped task state. Phase 1 only flows `submitted` and `completed`
 * through the inbox (one-shot delivery); the richer states are reserved
 * for Phase 2 / a2a-bridge.
 */
export enum TaskState {
  SUBMITTED = 'submitted',
  WORKING = 'working',
  INPUT_REQUIRED = 'input-required',
  COMPLETED = 'completed',
  CANCELED = 'canceled',
  FAILED = 'failed',
}
