import { oMethod } from '@olane/o-protocol';

export const LLM_PARAMS: { [key: string]: oMethod } = {
  completion: {
    name: 'completion',
    description: 'The primary method for interacting with the service',
    dependencies: [],
    parameters: [
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The model to use for generation',
        required: false,
      },
      {
        name: 'messages',
        type: 'array',
        value: 'string[]',
        description: 'The messages to use for generation',
      },
      {
        name: 'options',
        type: 'object',
        value: 'object',
        description: 'The options to use for generation',
        required: false,
      },
      {
        name: 'stream',
        type: 'boolean',
        value: 'boolean',
        description: 'Whether to stream the response',
        required: false,
      },
    ],
  },
  generate: {
    name: 'generate',
    description: 'Generate',
    dependencies: [],
    parameters: [
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The model to use for generation',
      },
      {
        name: 'stream',
        type: 'boolean',
        value: 'boolean',
        description: 'Whether to stream the response',
        required: false,
      },
    ],
  },
  list_models: {
    name: 'list_models',
    description: 'List models',
    dependencies: [],
    parameters: [],
  },
  pull_model: {
    name: 'pull_model',
    description: 'Pull model',
    dependencies: [],
    parameters: [
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The model to pull',
      },
      {
        name: 'insecure',
        type: 'boolean',
        value: 'boolean',
        description: 'Whether to allow insecure connections',
      },
    ],
  },
  delete_model: {
    name: 'delete_model',
    description: 'Delete model',
    dependencies: [],
    parameters: [
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The model to delete',
      },
    ],
  },
  model_info: {
    name: 'model_info',
    description: 'Model info',
    dependencies: [],
    parameters: [
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The model to get info for',
      },
    ],
  },
  status: {
    name: 'status',
    description: 'Status',
    dependencies: [],
    parameters: [],
  },
  embed_documents: {
    name: 'embed_documents',
    description: 'Generate embeddings for multiple documents',
    dependencies: [],
    parameters: [
      {
        name: 'input',
        type: 'array',
        value: 'string[]',
        description: 'Array of text strings to embed',
        required: true,
      },
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The embedding model to use',
        required: false,
      },
      {
        name: 'apiKey',
        type: 'string',
        value: 'string',
        description: 'OpenAI API key (optional, uses OPENAI_API_KEY env var if not provided)',
        required: false,
      },
      {
        name: 'dimensions',
        type: 'number',
        value: 'number',
        description: 'Number of dimensions for the embedding (only for text-embedding-3 models)',
        required: false,
      },
    ],
  },
  embed_query: {
    name: 'embed_query',
    description: 'Generate embedding for a single query string',
    dependencies: [],
    parameters: [
      {
        name: 'input',
        type: 'string',
        value: 'string',
        description: 'Text string to embed',
        required: true,
      },
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The embedding model to use',
        required: false,
      },
      {
        name: 'apiKey',
        type: 'string',
        value: 'string',
        description: 'OpenAI API key (optional, uses OPENAI_API_KEY env var if not provided)',
        required: false,
      },
      {
        name: 'dimensions',
        type: 'number',
        value: 'number',
        description: 'Number of dimensions for the embedding (only for text-embedding-3 models)',
        required: false,
      },
    ],
  },
  generate_image: {
    name: 'generate_image',
    description: 'Generate images using Gemini nano-banana models. Creates images from text prompts using gemini-2.5-flash-image or gemini-3-pro-image-preview.',
    dependencies: [],
    parameters: [
      {
        name: 'prompt',
        type: 'string',
        value: 'string',
        description: 'A text description of the desired image. Provide clear, detailed descriptions for best results.',
        required: true,
      },
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The model to use for image generation. Options: "gemini-2.5-flash-image" (default) or "gemini-3-pro-image-preview"',
        required: false,
      },
      {
        name: 'aspectRatio',
        type: 'string',
        value: 'string',
        description: 'Aspect ratio for the generated image. Options: "1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9". Default is "1:1".',
        required: false,
      },
      {
        name: 'imageSize',
        type: 'string',
        value: 'string',
        description: 'Size of the generated image. Options: "1K", "2K" (default), "4K". Higher values produce higher resolution images.',
        required: false,
      },
      {
        name: 'negativePrompt',
        type: 'string',
        value: 'string',
        description: 'Optional description of what to avoid in the generated image.',
        required: false,
      },
    ],
  },
  edit_image: {
    name: 'edit_image',
    description: 'Edit or transform an existing image using Gemini nano-banana models. Provide an image and instructions for how to modify it.',
    dependencies: [],
    parameters: [
      {
        name: 'prompt',
        type: 'string',
        value: 'string',
        description: 'Instructions for how to edit or transform the image. Be specific about desired changes.',
        required: true,
      },
      {
        name: 'image',
        type: 'string',
        value: 'string',
        description: 'Base64-encoded image data or file path to the image to edit. Supported formats: JPEG, PNG.',
        required: true,
      },
      {
        name: 'model',
        type: 'string',
        value: 'string',
        description: 'The model to use for image editing. Options: "gemini-2.5-flash-image" (default) or "gemini-3-pro-image-preview"',
        required: false,
      },
      {
        name: 'aspectRatio',
        type: 'string',
        value: 'string',
        description: 'Aspect ratio for the edited image. Options: "1:1", "2:3", "3:2", "3:4", "4:3", "4:5", "5:4", "9:16", "16:9", "21:9".',
        required: false,
      },
      {
        name: 'imageSize',
        type: 'string',
        value: 'string',
        description: 'Size of the edited image. Options: "1K", "2K" (default), "4K".',
        required: false,
      },
    ],
  },
};
