# name: oLane Network Private Release

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     permissions:
#       packages: write
#       contents: write

#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: 20
#           cache: npm

#       - name: Build client library
#         id: build-lib
#         env:
#           GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}
#         run: |
#           cat << EOF > .npmrc
#           @olane-labs:registry=https://npm.pkg.github.com
#           //npm.pkg.github.com/:_authToken=$GITHUB_TOKEN
#           EOF
#           npm ci
#           npm run build

#       - name: Publish Release
#         id: create-release
#         run: |
#           echo "Lets create a release"
#           git config --global user.email "bot@olane.com"
#           git config --global user.name "Automated Release"
#           npm version patch
#           # Change package name to @olane-labs/o-network before publish
#           sed -i 's/"name": "@olane\/o-network"/"name": "@olane-labs\/o-network"/' package.json
#           npm publish
#           sed -i 's/"name": "@olane-labs\/o-network"/"name": "@olane\/o-network"/' package.json
#           git push && git push --tags