name: oLane Version Release

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'release'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Build and test o-config
        working-directory: packages/o-config
        run: |
          npm i
          npm run build
          # npm run lint
          npm test

      - name: Build and test o-protocol
        working-directory: packages/o-protocol
        run: |
          npm i
          npm run build
          # npm run lint
          # npm test
      
      - name: Build and test root package
        run: |
          npm i
          npm run build
          # npm run lint
          npm test

      - name: Build and test o-tool
        working-directory: packages/o-tool
        run: |
          npm i
          npm run build
          # npm run lint
          npm test

      - name: Build and test o-tools-common
        working-directory: packages/o-tools-common
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test

      - name: Build and test o-tool-registry
        working-directory: packages/o-tool-registry
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test

      - name: Build and test o-network
        working-directory: packages/o-network
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test

  build-and-publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    environment: release

    permissions:
      contents: write
      id-token: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      # Build and test all packages sequentially
      - name: Install root dependencies
        run: npm ci

      - name: Build and test o-config
        working-directory: packages/o-config
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test

      - name: Build and test o-protocol
        working-directory: packages/o-protocol
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test
      
      - name: Build and test root package
        run: |
          npm run build
          # npm run lint
          # npm test

      - name: Build and test o-tool
        working-directory: packages/o-tool
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test

      - name: Build and test o-tools-common
        working-directory: packages/o-tools-common
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test

      - name: Build and test o-tool-registry
        working-directory: packages/o-tool-registry
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test

      - name: Build and test o-network
        working-directory: packages/o-network
        run: |
          npm ci
          npm run build
          # npm run lint
          # npm test
      

      - name: Config Git author
        run: |
          git config --global user.email "bot@olane.com"
          git config --global user.name "Automated Release"

      # Publish packages in dependency order
      - name: Publish o-config
        working-directory: packages/o-config
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish o-protocol
        working-directory: packages/o-protocol
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish root package (o-core)
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Wait for registry propagation
        run: sleep 5

      - name: Update o-tool dependencies and rebuild
        working-directory: packages/o-tool
        run: |
          # Update to use published versions instead of file dependencies
          npm install @olane/o-core@latest @olane/o-config@latest @olane/o-protocol@latest --save-peer
          npm run build

      - name: Publish o-tool
        working-directory: packages/o-tool
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Wait for registry propagation
        run: sleep 5

      - name: Update o-tools-common dependencies and rebuild
        working-directory: packages/o-tools-common
        run: |
          # Update to use published versions instead of file dependencies
          npm install @olane/o-core@latest @olane/o-config@latest @olane/o-protocol@latest @olane/o-tool@latest --save-peer
          npm run build

      - name: Publish o-tools-common
        working-directory: packages/o-tools-common
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Wait for registry propagation
        run: sleep 5

      - name: Update o-tool-registry dependencies and rebuild
        working-directory: packages/o-tool-registry
        run: |
          # Update to use published versions instead of file dependencies
          npm install @olane/o-core@latest @olane/o-config@latest @olane/o-protocol@latest @olane/o-tool@latest @olane/o-tools-common@latest --save-peer
          npm run build

      - name: Publish o-tool-registry
        working-directory: packages/o-tool-registry
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Wait for registry propagation
        run: sleep 5

      - name: Update o-network dependencies and rebuild
        working-directory: packages/o-network
        run: |
          # Update to use published versions instead of file dependencies
          npm install @olane/o-core@latest @olane/o-config@latest @olane/o-protocol@latest @olane/o-tool@latest @olane/o-tools-common@latest @olane/o-tool-registry@latest --save-peer
          npm run build

      - name: Publish o-network
        working-directory: packages/o-network
        run: |
          npm version patch --no-git-tag-version
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push version changes and create PR
        run: |
          git config --global user.email "bot@olane.com"
          git config --global user.name "Automated Release"
          BRANCH_NAME="version-change-$(date +%Y%m%d-%H%M%S)"
          git checkout -b $BRANCH_NAME
          git add .
          git commit -m "version changes"
          git push origin $BRANCH_NAME
          
          # Create draft PR
          gh pr create \
            --title "Automated Version Update - $(date +%Y-%m-%d)" \
            --body "This PR contains automated version updates from the release workflow." \
            --base main \
            --head $BRANCH_NAME \
            --draft
        env:
          GITHUB_TOKEN: ${{ secrets.CLASSIC_GITHUB_TOKEN }}